// Service worker: makes LocalLeet work offline.
// VERSION and PRECACHE are regenerated by `npm run build` (scripts/precache.mjs).
const VERSION = "fe6599d52111";
const PRECACHE = [
  "./",
  "index.html",
  "manifest.webmanifest",
  "css/app.css",
  "js/ai.js",
  "js/app.js",
  "js/editor.js",
  "js/llm-worker.js",
  "js/py-worker.js",
  "js/runner.js",
  "js/store.js",
  "problems/_util.js",
  "problems/chalk.js",
  "problems/classic-a.js",
  "problems/classic-b.js",
  "problems/index.js",
  "py/harness.py",
  "icons/apple-touch-icon.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png",
  "icons/icon.svg",
  "vendor/codemirror.js",
  "vendor/marked.js",
  "vendor/pyodide/pyodide-lock.json",
  "vendor/pyodide/pyodide.asm.mjs",
  "vendor/pyodide/pyodide.asm.wasm",
  "vendor/pyodide/pyodide.mjs",
  "vendor/pyodide/python_stdlib.zip"
];
const CACHE = `localleet-${VERSION}`;

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      // Add one by one so a single failure doesn't abort the whole install.
      await Promise.all(PRECACHE.map((url) => cache.add(new Request(url, { cache: "reload" })).catch((e) => console.warn("precache failed", url, e))));
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      for (const key of await caches.keys()) {
        if (key.startsWith("localleet-") && key !== CACHE) await caches.delete(key);
      }
      await self.clients.claim();
      for (const client of await self.clients.matchAll()) client.postMessage({ type: "precached", version: VERSION });
    })(),
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  const url = new URL(req.url);
  // Model downloads (Hugging Face etc.) are cached by the AI engines themselves.
  if (req.method !== "GET" || url.origin !== location.origin) return;

  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);
      const isPage = req.mode === "navigate";
      const key = isPage ? new URL("./index.html", location.href).href : url.origin + url.pathname;
      const hit = await cache.match(key);
      if (hit) return hit;
      try {
        const res = await fetch(req);
        // Cache everything same-origin we fetch (e.g. AI engine code loaded on demand).
        if (res.ok && res.type === "basic") cache.put(key, res.clone());
        return res;
      } catch (e) {
        if (isPage) {
          const shell = await cache.match(new URL("./index.html", location.href).href);
          if (shell) return shell;
        }
        throw e;
      }
    })(),
  );
});
